// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpH5Tl4-u92O5gjZ934CI8Ua4-0jIn77s',
    appId: '1:919772550920:web:ee4c084ef4ad0ed01fbebd',
    messagingSenderId: '919772550920',
    projectId: 'social-media-dashboard-44951',
    authDomain: 'social-media-dashboard-44951.firebaseapp.com',
    storageBucket: 'social-media-dashboard-44951.appspot.com',
    measurementId: 'G-HG3V0F29WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfyvqg44-mMbTJBei4B8-AgmLNtYbCLKM',
    appId: '1:919772550920:android:dabcb38f74a95e471fbebd',
    messagingSenderId: '919772550920',
    projectId: 'social-media-dashboard-44951',
    storageBucket: 'social-media-dashboard-44951.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoMO3yg80p_EZwR01clgct-ZaLahbp-xU',
    appId: '1:919772550920:ios:a5b97a7ce9aa15031fbebd',
    messagingSenderId: '919772550920',
    projectId: 'social-media-dashboard-44951',
    storageBucket: 'social-media-dashboard-44951.appspot.com',
    iosBundleId: 'com.example.flutterProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoMO3yg80p_EZwR01clgct-ZaLahbp-xU',
    appId: '1:919772550920:ios:b78fd919de64a4291fbebd',
    messagingSenderId: '919772550920',
    projectId: 'social-media-dashboard-44951',
    storageBucket: 'social-media-dashboard-44951.appspot.com',
    iosBundleId: 'com.example.flutterProject1.RunnerTests',
  );
}
